# fly.toml app configuration file generated for tg-jpg-cold-shape-8634 on 2024-12-17T00:20:03+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tg-jpg-cold-shape-8634'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
